### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by legramps** [themesberg/volt-laravel-dashboard#16]
Hi its my first time using the date picker, can you please provide an a working example on how to use it? I tried reading the docs but still can't do it. Thank you

**Comment by teamupdivision** [comment]
Hi @legramps,

Thank you for your message and for using our products.

Please find below detailed documentation to help you:
https://github.com/Pikaday/Pikaday

Also, here is an example of how to use it: https://codepen.io/adrianparr/pen/KwBNrv

Please let us know if this helped or if you need any additional info. 

Best,
UPDIVISION Team

**Comment by legramps** [comment]
Thank you :)
