### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by gbelvedere** [themesberg/volt-laravel-dashboard#22]
Hi, I managed to start a new project from the dashboard, but I can't find a way to create new pages. 
If I duplicate a view, and change it, is ok, and from the controllers, I can switch views. 
But if I make a new controller, or copy an existent one, and point it to any template, it renders as a blank page. It has content but the body is empty.

For instance this gives a blank page, please ignore de 401, is just a test to try something really simple

web.php
`Route::get('/401', Err401::class)->name('401');`

Err401.php
```
<?php
namespace App\Http\Livewire;
use Livewire\Component;

class Err401 extends Component
{
    public function render()
    {
        return view('500');//just return the same view than in Err500 
    }
}

```
Thank you

**Comment by teamupdivision** [comment]
Hello,

Thank you for using Creative TIM! 

In order to view a new route, you have to include it's name ('401' for example in your case) in 'app.blade.php' inside that array of routes on line 4. 

Let us know if that works. 

Thank you.

**Comment by gbelvedere** [comment]
well.. it works now... Is there any documentation on this kind of things?  as a quick start guide or something? I didn't see this in the docs...
thank you

**Comment by teamupdivision** [comment]
Hello, 

Sorry for late reply. 

There is no documentation for this issue as it is a pretty uncommon issues. 

As this ticket is considered done i will proceed with closing it. 

Thank you for using Creative TIM products. 

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
