### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Atamyrat2005** [themesberg/volt-laravel-dashboard#24]
**Good design but it is only dashboard designed site there is now working things.**  @Atamyrat2005

**Comment by teamupdivision** [comment]
Hello and thanks for using  Themesberg products.
For the free Volt Laravel dashboard you hava working, login, recover password, register and my profile built with Laravel.
All the best

**Comment by Atamyrat2005** [comment]
> Hello and thanks for using Themesberg products. For the free Volt Laravel dashboard you hava working, login, recover password, register and my profile built with Laravel. All the best

I am also full stack web developer You can visit my profile i can do more than working login, recover register etc... @Atamyrat2005
