### ISSUE TITLE
issue when installing dependancies

### ISSUE THREAD

**Issue by MdialloC19** [themesberg/volt-laravel-dashboard#25]
Hello 
I try installing the dependancies on my computer and got error : 
npm ERR! ../src/libsass/src/ast.hpp:1616:25: warning: loop variable ‘denominator’ creates a copy from type ‘const std::__cxx11::basic_string<char>’ [-Wrange-loop-construct]
npm ERR!  1616 |         for (const auto denominator : denominators)
npm ERR!       |                         ^~~~~~~~~~~
npm ERR! ../src/libsass/src/ast.hpp:1616:25: note: use reference type to prevent copying
npm ERR!  1616 |         for (const auto denominator : denominators)
npm ERR!       |                         ^~~~~~~~~~~
npm ERR!       |                         &
npm ERR! In file included from /home/mdialloc19/.node-gyp/16.20.1/include/node/v8.h:30,
npm ERR!                  from /home/mdialloc19/.node-gyp/16.20.1/include/node/node.h:73,
npm ERR!                  from ../../../../nan/nan.h:60,
npm ERR!                  from ../src/binding.cpp:1:
npm ERR! /home/mdialloc19/.node-gyp/16.20.1/include/node/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’:
npm ERR! /home/mdialloc19/.node-gyp/16.20.1/include/node/v8-internal.h:492:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
npm ERR!   492 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!       |                                      ^~~~~~~~~~~
npm ERR!       |                                      remove_cv
npm ERR! /home/mdialloc19/.node-gyp/16.20.1/include/node/v8-internal.h:492:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
npm ERR!   492 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!       |                                      ^~~~~~~~~~~
npm ERR!       |                                      remove_cv
npm ERR! /home/mdialloc19/.node-gyp/16.20.1/include/node/v8-internal.h:492:50: error: template argument 2 is invalid
npm ERR!   492 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!       |                                                  ^
npm ERR! /home/mdialloc19/.node-gyp/16.20.1/include/node/v8-internal.h:492:63: error: ‘::Perform’ has not been declared
npm ERR!   492 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!       |                                                               ^~~~~~~
npm ERR! ../src/binding.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE render(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! ../src/binding.cpp:284:80: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
npm ERR!   284 |     int status = uv_queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback);
npm ERR!       |                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! ../src/binding.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE render_file(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! ../src/binding.cpp:320:80: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
npm ERR!   320 |     int status = uv_queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback);
npm ERR!       |                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! In file included from ../../../../nan/nan.h:60,
npm ERR!                  from ../src/binding.cpp:1:
npm ERR! ../src/binding.cpp: At global scope:
npm ERR! /home/mdialloc19/.node-gyp/16.20.1/include/node/node.h:887:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
npm ERR!   887 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /home/mdialloc19/.node-gyp/16.20.1/include/node/node.h:921:3: note: in expansion of macro ‘NODE_MODULE_X’
npm ERR!   921 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR!       |   ^~~~~~~~~~~~~
npm ERR! ../src/binding.cpp:358:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR!   358 | NODE_MODULE(binding, RegisterModule);
npm ERR!       | ^~~~~~~~~~~
npm ERR! make: *** [binding.target.mk:133 : Release/obj.target/binding/src/binding.o] Erreur 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/mdialloc19/laravel/mutuelle/node_modules/gulp-sass/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 5.19.0-50-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/home/mdialloc19/laravel/mutuelle/node_modules/gulp-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/mdialloc19/laravel/mutuelle/node_modules/gulp-sass/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.20.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

**Comment by teamupdivision** [comment]
Hello, 

Thank you for using Creative TIM. 

Can you try using node v14 and let us know if that fixes the issue? 

Thank you.

**Comment by MdialloC19** [comment]
yes !! i fixed the issues with nodev16 and node-sass 9.0.0
Thank you!!! Keep in touch


Le lun. 7 août 2023 à 08:45, Updivision Team ***@***.***> a
écrit :

**Comment by teamupdivision** [comment]
Hello, 

Happy to hear everything turned out ok. 

If we can assist with anything else please let us know. 

Best
